### ISSUE TITLE
support for A6X Chauvet 2.15.29 Real-Time Recognition notes

### ISSUE THREAD

**Issue by ariccb** [jya-dev/supernote-tool#39]
I'm using `supernote-tool convert -t txt -a your.note output.txt` command but i'm receiving the error 

```Error extracting text from /Users/acbouwers/Library/Containers/5E209006-499F-43DC-BD7C-EC697B9B4D64/Data/Library/Application Support/com.ratta.supernote/677531935891181568/Supernote/Note/test FOLDER/20240628_133132.note: Command '['/opt/homebrew/bin/supernote-tool', 'convert', '-t', 'txt', '-a', '/Users/acbouwers/Library/Containers/5E209006-499F-43DC-BD7C-EC697B9B4D64/Data/Library/Application Support/com.ratta.supernote/677531935891181568/Supernote/Note/test FOLDER/20240628_133132.note', '/Users/acbouwers/Library/Containers/co.noteplan.NotePlan3/Data/Library/Application Support/co.noteplan.NotePlan3/Notes/00 - Inbox/20240628_133132_attachments/F20240628133148780701NNVSuxy4wGen_text.txt']' returned non-zero exit status 1.
Error output: Traceback (most recent call last):
  File "/opt/homebrew/bin/supernote-tool", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/supernotelib/cmds/supernote_tool.py", line 203, in main
    args.handler(args)
  File "/opt/homebrew/lib/python3.11/site-packages/supernotelib/cmds/supernote_tool.py", line 53, in subcommand_convert
    notebook = sn.load_notebook(args.input, policy=args.policy)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/supernotelib/parser.py", line 162, in load_notebook
    note = load(f, metadata, policy)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/supernotelib/parser.py", line 86, in load
    metadata = parse_metadata(stream, policy)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/supernotelib/parser.py", line 62, in parse_metadata
    raise exceptions.UnsupportedFileFormat('unsupported file format')
supernotelib.exceptions.UnsupportedFileFormat: unsupported file format```

I had this working prior to a software update on the a6x

**Comment by jya-dev** [comment]
Hi,
In my test, supernote-tool version 0.5.0 can parse note files created on A6X Chauvet2.15.29.
What version tool do you use?

You can check the version with below command:
```
$ pip show supernotelib | grep "^Version"
Version: 0.5.0
```

**Comment by ariccb** [comment]
You know what, it was totally me on my end. My command was mixing up png and pdf

**Comment by ariccb** [comment]
@jya-dev so one thing i'm wondering is if the supernote-tool can convert to .txt if the note wasn't originally saved as a real-time recognition file? When running my script, it converts the real-time recognition ones just fine, but outputs `Command output: no data` when it hits a regular .note file. 

The supernote tablet is capable of recognizing-then-converting these regular notes, so why not for supernote-tool?

**Comment by jya-dev** [comment]
Hi @ariccb 
Because realtime recognition files have text data that is recognized by Supernote tablet, supernote-tool extracts the text data from the note file.
Normal note files don't have such text data.
It could be converted to text using OCR technology, but that is beyond the scope of my tools.

**Comment by ariccb** [comment]
@jya-dev thanks so much for explaining that the regular note files don't contain the text data the same way. No problem that your tool wouldn't cover OCR functionality!!


I'm trying to figure out what metadata is possible to get from a .note file before trying to run any conversions on them, and I've been trying your `supernote-tool analyze file_name.note` command and no matter what type of .note file i run it on (standard, or Real-Time Recognition) it spits out this error:
```
➜ supernote-tool analyze 20240710_133322.note 
Traceback (most recent call last):
  File "/opt/homebrew/bin/supernote-tool", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/supernotelib/cmds/supernote_tool.py", line 203, in main
    args.handler(args)
  File "/opt/homebrew/lib/python3.11/site-packages/supernotelib/cmds/supernote_tool.py", line 49, in subcommand_analyze
    metadata = sn.parse_metadata(f, policy=args.policy)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/supernotelib/parser.py", line 62, in parse_metadata
    raise exceptions.UnsupportedFileFormat('unsupported file format')
supernotelib.exceptions.UnsupportedFileFormat: unsupported file format
```

Do you know if it's possible to get metadata like note-type info (real-time recognition vs standard), number of pages in a .note file, any Stars(their specific icon that saves a page location as a bookmark), or Keywords(tags), or Headings (used to be called titles), or Links (references to other .note files) ? I'm assuming that's what the analyze command is for, and would love to know how to use it properly.

**Comment by jya-dev** [comment]
Hi @ariccb,
Hmm, it seems that an error is occurring in your environment for some reason.
If you send me the note file where the error occurs I will investigate.
And `--policy=loose` option also might help you.
When this option is added, the tool tries to parse an unsupported note file. 
For example: `supernote-tool analyze --policy=loose your.note `

I have attached a note file and the output of `supernote-tool analyze` command.
(The note file is created on A6X Chauvet2.15.29.  supernote-tool version is v0.5.0)
[analyze-result.txt](https://github.com/user-attachments/files/16178674/analyze-result.txt)
[samplenote.zip](https://github.com/user-attachments/files/16178730/samplenote.zip)

I typed the following command:
```
$ supernote-tool analyze A6X_Chauvet2.15.29_standard_sample.note > analyze-result.txt
```

The output is JSON style.
If `FILE_RECOGN_TYPE` is `1`, the note is real-time recognition.  Otherwise standard note.
